language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - sourceline: 'ppa:antal.buss/boost'
          packages:
            - clang-3.8
            - g++-5
      env:
        - CLANG_VERSION=3.8
        - BOOST_VERSION=1.45

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:antal.buss/boost'
          packages:
            - g++-5
      env:
        - CC_VERSION=5
        - BOOST_VERSION=1.46

before_install:
  - |
    if [ -n "$CC_VERSION" ]; then
      export CXX="g++-${CC_VERSION}" CC="gcc-${CC_VERSION}"
    fi

    if [ -n "$CLANG_VERSION" ]; then
      export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"
    fi

    $CC -v

install:
    sudo apt install libboost${BOOST_VERSION}-all-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    -  make VERBOSE=1 && ./KLP ../corpus.txt ../dic.txt '买水果然后去世博园'
