language: cpp
sudo: required

env:
    - CC_VERSION=5
    - CC_VERSION=6

env:
    - BOOST_VERSION=1.61 CC_VERSION=5
    - BOOST_VERSION=1.61 CC_VERSION=6
    - BOOST_VERSION=1.62 CC_VERSION=5
    - BOOST_VERSION=1.62 CC_VERSION=6
    - BOOST_VERSION=1.63 CC_VERSION=5 
    - BOOST_VERSION=1.63 CC_VERSION=6 
 
before_install:
  - |
    sudo add-apt-repository 'ppa:ubuntu-toolchain-r/test'
    sudo add-apt-repository 'ppa:rexut/factory'
    sudo apt install g++-${CC_VERSION} 
    export CXX="g++-${CC_VERSION}" CC="gcc-${CC_VERSION}"
    $CC -v

install:
    sudo apt install libboost${BOOST_VERSION}-all-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    -  make VERBOSE=1 && ./KLP ../corpus.txt ../dic.txt '买水果然后去世博园'
