language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-5.0
          packages:
            - clang-5.0
      env:
        - CLANG_VERSION=5.0

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC_VERSION=5

before_install:
  - |
    if [ -n "$CC_VERSION" ]; then
      export CXX="g++-${CC_VERSION}" CC="gcc-${CC_VERSION}"
    fi

    if [ -n "$CLANG_VERSION" ]; then
      export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"
    fi

install:
    - sudo apt-get install libboost-all-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    -  make VERBOSE=1 && ./KLP ../corpus.txt ../dict.tt '我来到网易杭研院'
