name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: setup-env
      run: sudo apt-get install libboost-all-dev
    - name: create_build_dir
      run: mkdir ./build
    - name: cmake
      run: cd build && cmake ..
    - name: make
      run: cd build && make
    - name: make clean
      run: cd build && make clean
